name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
      
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 12']
        swift-version: [5.3]

    steps:
    - uses: actions/checkout@v2
    - name: Pod Install
      run: pod install
    - name: Archive for iOS Device slice
      run: xcrun xcodebuild archive -quiet -workspace AnyImageKit.xcworkspace -scheme AnyImageKit -configuration Release -destination "generic/platform=iOS" -archivePath "Build/AnyImageKit-iphoneos.xcarchive" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
    
  iOS_Simulator:
    name: Test iOS Simulator
    runs-on: macOS-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 12']
        swift-version: [5.3]

    steps:
    - uses: actions/checkout@v2
    - name: Pod Install
      run: pod install
    - name: Archive for iOS Simulator slice
      run: xcrun xcodebuild archive -quiet -workspace AnyImageKit.xcworkspace -scheme AnyImageKit -configuration Release -destination "generic/platform=iOS Simulator" -archivePath "Build/AnyImageKit-iphonesimulator.xcarchive" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
    
  Mac_Catalyst:
    name: Test Mac Catalys
    runs-on: macOS-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
      
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 12']
        swift-version: [5.3]
    
    steps:
    - uses: actions/checkout@v2
    - name: Pod Install
      run: pod install
    - name: Archive for Mac Catalyst slice
      run: xcrun xcodebuild archive -quiet -workspace AnyImageKit.xcworkspace -scheme AnyImageKit -configuration Release -destination "platform=macOS,arch=x86_64,variant=Mac Catalyst" -archivePath "Build/AnyImageKit-catalyst.xcarchive" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES

  CocoaPods:
    name: CocoaPods Library Lint
    runs-on: macOS-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 12']
        swift-version: [5.3]

    steps:
    - uses: actions/checkout@v2
    - name: Library Lint Check
      run: pod lib lint
